### PR TITLE
Update Subdomain Registrar To Set Address Resolution Atomically

### PR DESCRIPTION
**Pull request by apbendi**
Without setting the address, properly validated reverse resolution will not work.

### CODE REVIEW

**Review by mds1 — APPROVED** [review]
LGTM!

**Comment by mds1** [comment]
Should we also do the new deployment in this PR?

**Comment by apbendi** [comment]
@mds1 PR is updated to include the latest deployment to rinkeby & mainnet. LMK if it's good to merge!

**Comment by mds1** [comment]
Looks like this PR was complete, so merging it as part of some general github triage of PRs. @apbendi Using a squash merge in case you disagree and want to revert the commit

**Pull request merged**
